// Game constants - Single source of truth for magic numbers

export const GAME_CONSTANTS = {
  // Map dimensions
  MAP_SIZE: 100,
  HALF_MAP_SIZE: 50,
  MAP_BOUNDARY_BUFFER: 2,

  // Spawn settings
  SPAWN_CLEARANCE_RADIUS: 15,
  MIN_OBSTACLE_SPACING: 8,

  // Enemy limits
  MAX_ENEMIES: 20,
  MAX_TURRETS: 3,

  // Terrain generation
  DEFAULT_OBSTACLE_COUNT: 20,
  MAX_SPAWN_ATTEMPTS: 500,

  // Tank physics
  TANK_RADIUS: 1.25,
  BOMBER_RADIUS: 1.2,
  TURRET_COLLISION_RADIUS: 1.5,
  OBSTACLE_RADIUS_MULTIPLIER: 0.75,

  // Combat
  COIN_DROP_CHANCE: 0.05,
  DEFAULT_COIN_VALUE: 1,
  HEALTH_PACK_HEAL_AMOUNT: 25,
  BOMBER_EXPLOSION_DAMAGE: 25,
  BOMBER_EXPLOSION_RANGE: 2,

  // Safe zone
  SAFE_ZONE_INITIAL_RADIUS: 50,
  SAFE_ZONE_MIN_RADIUS: 5,
  SAFE_ZONE_RADIUS_DECREASE_PER_TIER: 4,
  SAFE_ZONE_ACTIVATION_LEVEL: 5,
  SAFE_ZONE_BASE_DAMAGE: 1,
  SAFE_ZONE_DEFAULT_SHRINK_RATE: 0.05,
  SAFE_ZONE_MAX_SHRINK_RATE: 0.15,

  // Player defaults
  PLAYER_INITIAL_HEALTH: 100,
  PLAYER_INITIAL_SPEED: 3,
  PLAYER_INITIAL_FIRE_RATE: 2, // seconds between shots
  PLAYER_INITIAL_CAMERA_RANGE: 8,
  PLAYER_INITIAL_BULLET_VELOCITY: 15,
  PLAYER_INITIAL_TURRET_DAMAGE: 50,
  PLAYER_MAX_CAMERA_RANGE: 14,
  PLAYER_MAX_FIRE_RATE: 3.5, // shots per second
  PLAYER_MAX_PENETRATION: 3,

  // Enemy stats
  ENEMY_TANK_BASE_HEALTH: 75,
  ENEMY_HEALTH_SCALE_PER_LEVEL: 9,
  ENEMY_TANK_SHOOTING_RANGE: 20,
  ENEMY_TURRET_SHOOTING_RANGE: 25,
  ENEMY_TANK_FIRE_RATE: 5.0,
  ENEMY_TURRET_FIRE_RATE: 6.0,

  // Movement speeds
  ENEMY_TANK_BASE_SPEED: 1.5,
  ENEMY_BOMBER_BASE_SPEED: 2.5,
  ENEMY_TANK_TURN_RATE: 1.0,
  ENEMY_BOMBER_TURN_RATE: 2.0,

  // Camera animation
  INTRO_PAN_DURATION: 5.0,
  INTRO_CAMERA_HEIGHT: 40,
  INTRO_CAMERA_DISTANCE: 60,
  INTRO_CAMERA_FOV: 50,
  DEFAULT_CAMERA_FOV: 60,
  FIRST_PERSON_FOV: 75,

  // First-person view (anti-nausea)
  FPV_FOV: 62,
  FPV_EYE_HEIGHT: 1.2,
  FPV_FORWARD_OFFSET: 0.3,
  FPV_POSITION_LERP_FACTOR: 4.0,
  FPV_ROTATION_LERP_FACTOR: 6.0,
  FPV_TRANSITION_DURATION: 0.5,
  FPV_PITCH_ANGLE: -0.05,
  FPV_LOOK_AHEAD_DISTANCE: 10.0,

  // Weapon positioning
  SIDE_WEAPON_DISTANCE: 2.75,
  SIDE_WEAPON_Y_OFFSET: 0.0,
  MAX_SIDE_WEAPONS: 4,

  // Level progression
  EARLY_GAME_MAX_LEVEL: 24,
  MID_GAME_MAX_LEVEL: 50,
  UPGRADE_UI_MAX_LEVEL: 50,
  WEAPON_SELECTION_LEVELS: [10, 20, 30, 40] as const,
} as const;

// Derived constants for convenience
export const TANK_COLLISION_BUFFER = GAME_CONSTANTS.TANK_RADIUS + 0.1;
export const OBSTACLE_COLLISION_BUFFER = 0.1;

// Type for game constants (useful for TypeScript consumers)
export type GameConstants = typeof GAME_CONSTANTS;
